### PR TITLE
Replace fixed border with block border control

### LINKED ISSUE #3: Replace fixed border with block border control
Fundraising blocks always include a small grey border. As this default styling is not very common in default blocks and to give users more control over the block appearance, it would be better to remove the border and add support for the default block border control instead.

Fixed border

### PR DESCRIPTION
**Pull request by rvdsteege**
Fix #3.

Block border control

### CODE REVIEW

**Comment by rvdsteege** [comment]
ℹ️ Adding block support for `__experimentalBorder` still seems current for WordPress `6.1.1`.

- https://github.com/WordPress/WordPress/blob/c927cb503affd9182a6d4d39f0cadf4e10523cda/wp-includes/block-supports/border.php#L137-L165

**Comment by remcotolsma** [comment]
I just tried this, but i don't see block border controls.

Scherm­afbeelding 2023-02-22 om 14 38 52

<details>
<summary>Site Health Info</summary>

```
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: undefined
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: loading...
uploads_path: /var/www/html/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/html/wp-content/themes
themes_size: loading...
plugins_path: /var/www/html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.0
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor
theme_path: /var/www/html/wp-content/themes/twentytwentythree
auto_update: Disabled

### wp-themes-inactive (12) ###

Twenty Eleven: version: 4.2, author: the WordPress team, Auto-updates disabled
Twenty Fifteen: version: 3.3, author: the WordPress team, Auto-updates disabled
Twenty Fourteen: version: 3.5, author: the WordPress team, Auto-updates disabled
Twenty Nineteen: version: 2.4, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 3.1, author: the WordPress team, Auto-updates disabled
Twenty Sixteen: version: 2.8, author: the WordPress team, Auto-updates disabled
Twenty Ten: version: 3.7, author: the WordPress team, Auto-updates disabled
Twenty Thirteen: version: 3.7, author: the WordPress team, Auto-updates disabled
Twenty Twelve: version: 3.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 2.1, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.7, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.3, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (8) ###

Gutenberg: version: 15.1.1, author: Gutenberg Team, Auto-updates disabled
One Time Login: version: 0.3.1, author: Daniel Bachhuber, Auto-updates disabled
Plugin Dependencies: version: 1.7.7, author: Andy Fragen, Colin Stewart, Auto-updates disabled
Pronamic Client: version: 1.9.7, author: Pronamic, Auto-updates disabled
Pronamic Pay: version: 9.3.5, author: Pronamic, Auto-updates disabled
Pronamic Pay Fundraising Add-On: version: 3.1.1, author: Pronamic, Auto-updates disabled
Pronamic Pay Test Helper: version: 1.0.0, author: Pronamic, Auto-updates disabled
Query Monitor: version: 3.11.1, author: John Blackbourn, Auto-updates disabled

### wp-plugins-inactive (1) ###

Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: 9.53.3

### wp-server ###

server_architecture: Linux 5.15.49-linuxkit x86_64
httpd_software: Apache/2.4.54 (Debian)
php_version: 8.0.28 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.74.0 OpenSSL/1.1.1n
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.11.2-MariaDB-1:10.11.2+maria~ubu2204
client_version: mysqlnd 8.0.28
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: http://localhost:8888/
WP_SITEURL: http://localhost:8888/
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pronamic-pay ###

license_status: undefined
next_license_check: Wed 22 Feb 2023 at 13:33
time: 2023/02/22 1:39:39 PM
openssl_version: OpenSSL 1.1.1n  15 Mar 2022
active_plugin_integrations: None
active_gateway_integrations: None
````
</details>

**Comment by rvdsteege** [comment]
@remcotolsma wrong branch? Looks (the 1px grey border) like you're not on https://github.com/pronamic/wp-pronamic-pay-fundraising/tree/3-block-border-control ?

**Comment by remcotolsma** [comment]
Scherm­afbeelding 2023-02-22 om 14 53 54

Found it.

**Review by remcotolsma — COMMENTED** [review]
Ok.

**Pull request merged**
